### ISSUE TITLE
One-directional sync?

### ISSUE THREAD

**Issue by k4y4k** [bergercookie/taskwarrior-syncall#25]
Howdy :wave:

I use tools such as `bugwarrior` with my install of `task`, and such, prefer to use task as a sort of overview as well as a todo list. Queries such as `task +DUETODAY` are never too far behind in my shell history :smile: 

Here's my question:

I have a bazillion google calendars to keep track of. I don't want to edit all of these (aside from maybe 1 or 2). **Can I _just_ pull in events** from calendars?

Cheers!
  kayak

**Comment by bergercookie** [comment]
Hi, sorry for the late reply,

Currently one-directional sync isn't possible, I'm afraid.
I'll keep this issue around though in case I find some time to work on it

**Comment by k4y4k** [comment]
No worries :+1:

**Comment by bergercookie** [comment]
Closing this since one-way sync is still not not in scope for this tool
