### ISSUE TITLE
[tw_gcal_sync] latency between edit and sync

### ISSUE THREAD

**Issue by jonathanbcarlson** [bergercookie/taskwarrior-syncall#36]
After creating a task in TW, how quickly will the associated gcal calendar update?

I saw that the synchronizer being used ([item-synchronizer](https://github.com/bergercookie/item_synchronizer)) is event-driven (e.g., if a task is added/edited it updates the other side) so I'm not sure why there's such a delay (> 1 hour).
I'd love to use this sync functionality but it seems like I'll need to use the `cron` sync method.

I'm on macOS 12.3 on an M1 mac running Python 3.9.10, let me know if I can help debug.

Thanks for the all work you've done, I appreciate it!

**Comment by bergercookie** [comment]
Hi @jonathanbcarlson ,

> I saw that the synchronizer being used ([item-synchronizer](https://github.com/bergercookie/item_synchronizer)) is event-driven

No, it's not event-driven. The calling code, eg.., `taskw_gcal_sync` initializes the `ItemSynchronizer` and registers methods that should be executed, e.g., on event addition, removal, etc.

Thus, as it's not event-driven, you have to use periodically, with something like cron, to run the `taskw_gcal_sync` script. See the README for details: https://github.com/bergercookie/taskwarrior-syncall#mechanics--automatic-synchronization=

**Comment by jonathanbcarlson** [comment]
I see, thanks.
