### ISSUE TITLE
Needs Browser error

### ISSUE THREAD

**Issue by guilhermeprokisch** [bergercookie/taskwarrior-syncall#38]
I'm trying to setup google keep sync but I'm getting the following error

```
<class \'gkeepapi.exception.LoginException\'>\n          -> <module \'gkeepapi.exception\' from \'/usr/local/lib/python3.9/site-packages/gkeepapi/exception.py\'>\n\ngkeepapi.exception.LoginException: (\'NeedsBrowser\', \'To access your account, you must sign in on the web. Touch Next to start browser sign-in.\')\n'
Arguments: ()
```

**Comment by bergercookie** [comment]
Hi there,

I've trimmed your description to avoid potentially exposing your credentials.
Please take a look at the snippet before pasting next time, and consider changing the password to this account if it's an account you use. :) :)

To the issue at hand, this is a known issue with `gkeepapi` that I'm using under the hood.

There's a good FAQ section here on how to solve -  https://gkeepapi.readthedocs.io/en/latest/#faq

I would suggest that you enable a direct password to your account if you have 2FA.

Also related:

* https://github.com/kiwiz/gkeepapi/issues/81
* https://github.com/kiwiz/gkeepapi/issues/95
