### ISSUE TITLE
Option to have deleted events from Google Calendar show as completed tasks in taskwarrior

### ISSUE THREAD

**Issue by StefanBRas** [bergercookie/taskwarrior-syncall#9]
Hi.

I would like to request the feature to have deleted events from Google Calendar show as completed tasks in Taskwarrior.

Right now, to do so (I believe) that one would have to open the event and manually change "pending" to "completed".

If this was implemented, it would be much faster to mark tasks as done via Google Calendar and i believe that people more often mark a task as "done" as opposed to delete it.

This probably sounds odd and/or unnecessary, but hopefully it makes sense if you see my setup which i have described in #8 .

It probably sounds like a bit of an convoluted setup, but I find it much better than existing Android Taskwarrior apps.

**Comment by bergercookie** [comment]
Hey @StefanBRas ,

Thanks for the interest in the plugin. :-)
Let me take a look at it in the next coiuple of days.

It does sound like a reasonable feature and it should be relatively straightforward to implement using an extra variable in the yaml file., something like `gcal_deleted_as_taskw_done: true`

**Comment by bergercookie** [comment]
Would require changes to the `item_synchronizer` and that's not really worth it IMO.
Closing this.
